# Generated by Django 6.0.5 on 2026-06-11 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='media',
        ),
    ]
