# Generated by Django 6.0.5 on 2026-06-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='caption',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
